#
# Module script for module 'UiPathOrch'
#
# Generated by: Yoshifumi Tsuda
#
# Generated on: 2023/08/28
#

#Set-Alias -Name job -Value Get-OrchJob
#Set-Alias -Name log -Value Get-OrchLog
#Set-Alias -Name stop -Value Stop-OrchJob

Set-Alias -Name !Show-OrchGuide -Value Get-OrchHelp

. $PSScriptRoot\Functions\Enable-OrchUserAttended.ps1
. $PSScriptRoot\Functions\Disable-OrchUserAttended.ps1

. $PSScriptRoot\Functions\Enable-OrchPersonalWorkspace.ps1
. $PSScriptRoot\Functions\Disable-OrchPersonalWorkspace.ps1

. $PSScriptRoot\Functions\Find-OrchFolderNoUserAssigned.ps1

. $PSScriptRoot\Functions\Get-OrchJobVideo.ps1

. $PSScriptRoot\Functions\Format-OrchQueueItem.ps1
. $PSScriptRoot\Functions\Format-OrchTestDataQueueItem.ps1

# Extend QueueItem with an Expanded property that flattens SpecificContent keys into a PSCustomObject.
# (SpecificContent is the Dictionary form; SpecificData is the same content serialized as JSON string.)
# Use: Get-OrchQueueItem ... | ForEach-Object Expanded | Format-Table
# For mixed-queue output, pipe to Format-OrchQueueItem to group by QueueDefinitionId first.
Update-TypeData -TypeName UiPath.PowerShell.Entities.QueueItem `
    -MemberName Expanded -MemberType ScriptProperty -Force -Value {
        $p = [ordered]@{}
        'Id','Reference','Status','Priority','DeferDate','DueDate','StartProcessing','EndProcessing' |
            ForEach-Object { $p[$_] = $this.$_ }
        if ($this.SpecificContent) {
            foreach ($k in ($this.SpecificContent.Keys | Sort-Object)) {
                $p[$k] = $this.SpecificContent[$k]
            }
        }
        [pscustomobject]$p
    }
