#
# Module script for module 'UiPath.PowerShell.OrchProvider'
#
# Generated by: Yoshifumi Tsuda
#
# Generated on: 2023/08/28
#


Set-Alias -Name job -Value Get-OrchJob
Set-Alias -Name log -Value Get-OrchLog
Set-Alias -Name stop -Value Stop-OrchJob

