#
# Module manifest for module 'UiPath.PowerShell.OrchProvider'
#
# Generated by: Yoshifumi Tsuda
#
# Generated on: 2023/08/28
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'UiPathOrch.psm1'

# Version number of this module.
ModuleVersion = '0.9.8.11'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '7098583d-d092-4fe9-bf36-a652e7a51efb'

# Author of this module
Author = 'Yoshifumi Tsuda'

# Company or vendor of this module
CompanyName = 'UiPath'

# Copyright statement for this module
Copyright = '(c) UiPath All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell providers for managing UiPath Orchestrator entities via cmdlets.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4.2'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('OrchProvider.Format.ps1xml')


# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('UiPath.PowerShell.OrchProvider.dll')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
'Get-OrchTestDataQueueItemTable',
'Enable-OrchUserAttended',
'Disable-OrchUserAttended',
'Enable-OrchPersonalWorkspace',
'Disable-OrchPersonalWorkspace',
'Find-OrchFolderNoUserAssigned',
'Get-OrchJobVideo'
)


# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
'Get-OrchLibrary',
'Get-OrchLibraryVersion',
'Remove-OrchLibrary',
'Import-OrchLibrary',
'Export-OrchLibrary',
'Copy-OrchLibrary',

'Get-OrchPackage',
'Copy-OrchPackage',
'Get-OrchPackageVersion',
'Remove-OrchPackage',
'Import-OrchPackage',
'Export-OrchPackage',

'Get-OrchJob',
'Start-OrchJob',
'Stop-OrchJob',
'Open-OrchJob',

'Get-OrchLog',
'Get-OrchAuditLog',

'Get-OrchJobMedia',
'Export-OrchJobMedia',
'Remove-OrchJobMedia',

'Get-OrchProcess',
'Add-OrchProcess',
'Update-OrchProcess',
'Copy-OrchProcess',
'Remove-OrchProcess',
'Edit-OrchProcess',
'Update-OrchProcessVersion',
'Reset-OrchProcessVersion',

'Get-OrchRobot',

'Get-OrchUser',
'Add-OrchUser',
'Update-OrchUser',
'Copy-OrchUser',
'Remove-OrchUser',
'Remove-OrchRoleFromUser',
'Get-OrchCurrentUser',
'Update-OrchCurrentUserURPassword',

'Get-OrchLicenseNamedUser',
'Get-OrchLicenseRuntime',
'Enable-OrchLicenseRuntime',
'Disable-OrchLicenseRuntime',

'Get-OrchPmAuditLog',

'Get-OrchPmLicensedUser',

'Get-OrchPmLicensedGroup',
'Remove-OrchPmLicensedGroup',
'Add-OrchPmLicenseToPmLicensedGroup',
'Remove-OrchPmAllocationFromPmLicensedGroup',
'Remove-OrchPmLicenseFromPmLicensedGroup',

'Get-OrchClassicRobot',
'Get-OrchClassicEnvironment',

'Get-OrchUserSession',
'Get-OrchMachineSession',
'Get-OrchUnattendedSession',

'Enable-OrchMaintenanceMode',
'Disable-OrchMaintenanceMode',

'Get-OrchJobStats',
'Get-OrchLicenseStats',

'Get-OrchRole',
'Set-OrchRole',
'Remove-OrchRole',
'Copy-OrchRole',

'Get-OrchCalendar',
'Remove-OrchCalendar',
'Copy-OrchCalendar',

'Add-OrchCalendarDate',
'Remove-OrchCalendarDate',

'Get-OrchPersonalWorkspace',
'Remove-OrchPersonalWorkspace',
'Get-OrchFolderUsage',

'Get-OrchFolderUser',
'Add-OrchFolderUser',
'Copy-OrchFolderUser',
'Move-OrchFolderUser',
'Remove-OrchFolderUser',

'Add-OrchRoleToFolderUser',
'Remove-OrchRoleFromFolderUser',

'Get-OrchMachine',
'Update-OrchMachine',
'Add-OrchMachine',
'Remove-OrchMachine',
'Copy-OrchMachine',
'Get-OrchMachineClientSecretId',
'Add-OrchMachineClientSecret',
'Remove-OrchMachineClientSecret',

'Get-OrchFolderMachine',
'Add-OrchFolderMachine',
'Copy-OrchFolderMachine',
'Remove-OrchFolderMachine',
'Enable-OrchFolderMachineInherit',
'Disable-OrchFolderMachineInherit',

'Get-OrchAsset',
'Set-OrchAsset',
'Copy-OrchAsset',
'Remove-OrchAsset',

'Set-OrchCredentialAsset',

'Get-OrchCredentialStore',
'Copy-OrchCredentialStore',
'Remove-OrchCredentialStore',

'Get-OrchAssetLink',
'Add-OrchAssetLink',

'Get-OrchTrigger',
'Add-OrchTrigger',
'Update-OrchTrigger',
'Remove-OrchTrigger',
'Copy-OrchTrigger',
'Enable-OrchTrigger',
'Disable-OrchTrigger',

'Get-OrchApiTrigger',
'Remove-OrchApiTrigger',
'Copy-OrchApiTrigger',
'Enable-OrchApiTrigger',
'Disable-OrchApiTrigger',

'Get-OrchQueue',
'Add-OrchQueue',
'Update-OrchQueue',
'Copy-OrchQueue',
'Remove-OrchQueue',

'Get-OrchQueueItem',
'Import-OrchQueueItem',

'Get-OrchTestSet',
'Copy-OrchTestSet',
'Remove-OrchTestSet',
'Start-OrchTestSet',

'Get-OrchTestCase',
'Get-OrchTestCaseExecution',
'Remove-OrchTestCase',

'Get-OrchTestSetExecution',
'Stop-OrchTestSetExecution',

'Get-OrchTestSetSchedule',
'Copy-OrchTestSetSchedule',
'Remove-OrchTestSetSchedule',
'Enable-OrchTestSetSchedule',
'Disable-OrchTestSetSchedule',

'Get-OrchTestDataQueue',
'Copy-OrchTestDataQueue',
'Remove-OrchTestDataQueue',

'Get-OrchTestDataQueueItem',
'Reset-OrchTestDataQueueItem',

'Get-OrchAlert',

'Get-OrchBucket',
'Add-OrchBucket',
'Copy-OrchBucket',
'Remove-OrchBucket',

'Get-OrchBucketItem',

'Get-OrchWebhook',
'Copy-OrchWebhook',
'Remove-OrchWebhook',
'Enable-OrchWebhook',
'Disable-OrchWebhook',

'Get-OrchSetting',
'Get-OrchExecutionSetting',
'Get-OrchWebSetting',
'Get-OrchAuthenticationSetting',
'Get-OrchActivitySetting',
'Get-OrchConnectionString',
'Get-OrchLicense',
'Get-OrchUpdateSetting',

'Get-OrchActionCatalog',
'Copy-OrchActionCatalog',
'Remove-OrchActionCatalog',

'Get-OrchPmUser',
'Update-OrchPmUser',
'Remove-OrchPmUser',
'Add-OrchPmUserBulk',
'Copy-OrchPmUser',

'Get-OrchPmRobotAccount',
'Set-OrchPmRobotAccount',
'Copy-OrchPmRobotAccount',
'Remove-OrchPmRobotAccount',

'Get-OrchPmGroup',
'Add-OrchPmGroup',
'Remove-OrchPmGroup',
'Add-OrchPmGroupMember',
'Move-OrchPmGroupMember',
'Remove-OrchPmGroupMember',

'Get-OrchPmExternalApiResource',
'Get-OrchPmExternalApplication',

'Get-DuRole',
'Get-DuUser',
'Get-DuDocumentType',
'Get-DuClassifier',
'Get-DuExtractor',

'Get-TmConfiguration',
'Get-TmProjectSetting',
'Get-TmProjectPermission',
'Get-TmServerInfo',

'Get-TmRequirement',
'Remove-TmRequirement',

'Get-TmTestCase',
'Remove-TmTestCase',

'Get-TmTestSet',
'Remove-TmTestSet',

'Clear-OrchCache',
'Edit-OrchConfig',
'Get-OrchPSDrive',
'Set-OrchLocation'
)

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
#AliasesToExport = @('job', 'log', 'stop')

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '- When RedirectUrl was set at the root level of the configuration file, connections to confidential app settings could not be established.

- Previously, each entity used a distinct cache implementation, despite the code being nearly identical. To streamline maintenance, the common code has now been extracted and unified. This change improves code maintainability and slightly reduces the module''s footprint. Additionally, several minor issues were fixed in the process.

- In the former implementation of Get-OrchLog, logs sorted by TimeStamp could retrieve over 10,000 rows by generating an OData query based on the TimeStamp value of the last row fetched. However, this approach sometimes caused log rows on page boundaries to be missed. Therefore, the automatic page splitting by TimeStamp values has been removed. This change is expected to improve functionality, though as a trade-off, it is no longer possible to retrieve over 10,000 log rows at once. If needed, please adjust the query parameters manually and execute the Get-OrchLog cmdlet in segments. Then, by running the Get-OrchLog cmdlet without parameters, the cached log rows can be combined and output.

- The Get-OrchQueueItem cmdlet has been enhanced.
  - In Automation Cloud, the number of queue items that can be retrieved at once is limited to 100. Previously, specifying -First 100 was required when executing the Get-OrchQueueItem cmdlet to obtain the expected results. This limitation has been removed by automatically paginating in increments of 100 rows.

  - The DateTime values returned by the Get-OrchQueueItem cmdlet (such as DueDate, DeferDate, etc.) are now output in the local time zone. Previously, the default view displayed DateTime values in the local time zone, but they appeared in UTC format when redirected via a pipeline.

  - Several query parameters (such as -DueDateAfter and -DueDateBefore) have been added.

  - The Get-OrchQueueItem cmdlet now displays a progress bar.
'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
