using UiPath.PowerShell.Core;
using Xunit;

namespace UnitTests;

// IdentityUrl auto-generation in CascadePSDriveFromGlobalSettings derives the
// Identity Server URL from Root when the user hasn't pinned it explicitly.
// The rules are documented in UiPathOrchConfig.cs alongside the implementation;
// this suite locks them in so a future refactor can't silently regress AS.
public class IdentityUrlAutoGenTests
{
    [Theory]
    // Cloud: tenant stripped, /{org}/identity_
    [InlineData("https://cloud.uipath.com/myorg/mytenant",
                "https://cloud.uipath.com/myorg/identity_")]
    // Automation Suite: identity is a host-level service (confirmed against
    // BMW's 2023.4 deployment). NO org segment in the auto-derived URL.
    [InlineData("https://rpa-emea-int.eu-central-1.aws.cloud.bmw/Default/Default",
                "https://rpa-emea-int.eu-central-1.aws.cloud.bmw/identity_")]
    [InlineData("https://as.example.com/Default/Default",
                "https://as.example.com/identity_")]
    // On-premises with tenant in path: tenant stripped, /identity at host root
    [InlineData("https://orchestrator.local/mytenant",
                "https://orchestrator.local/identity")]
    // On-premises with no tenant in path (single-tenant Orchestrator on Azure
    // App Service / standalone MSI): /identity at host root
    [InlineData("https://orchestrator.local",
                "https://orchestrator.local/identity")]
    [InlineData("https://my-orch.azurewebsites.net",
                "https://my-orch.azurewebsites.net/identity")]
    public void IdentityUrl_AutoGenerated_FromRoot(string root, string expected)
    {
        var drive = new PSDrive { Root = root };
        drive.CascadePSDriveFromGlobalSettings(null);
        Assert.Equal(expected, drive.IdentityUrl);
    }

    [Fact]
    public void IdentityUrl_ExplicitValue_NotOverridden()
    {
        // When the user pins IdentityUrl explicitly, auto-gen must not touch it,
        // even if the Root would imply a different value. This is how Cosmin's
        // BMW config worked before 1.1.0 added AS support — he had pinned
        // /identity_ at host root manually.
        var drive = new PSDrive
        {
            Root = "https://as.example.com/Default/Default",
            IdentityUrl = "https://custom.identity.example.com/identity_",
        };
        drive.CascadePSDriveFromGlobalSettings(null);
        Assert.Equal("https://custom.identity.example.com/identity_", drive.IdentityUrl);
    }

    [Fact]
    public void IdentityUrl_ExplicitEdition_OverridesHeuristic()
    {
        // Edition pin "OnPremises" on a 2-segment Root flips auto-gen back to
        // the on-prem path — the escape hatch documented in Troubleshooting for
        // on-prem behind a multi-level reverse proxy that produces
        // /dept/tenant. Without the pin, the heuristic would classify it as AS
        // and emit /identity_ at host root, which would be wrong for true on-prem.
        var drive = new PSDrive
        {
            Root = "https://gateway.corp/dept/tenant",
            Edition = "OnPremises",
        };
        drive.CascadePSDriveFromGlobalSettings(null);
        Assert.Equal("https://gateway.corp/dept/identity", drive.IdentityUrl);
    }
}
